title: <p align="center"> Syed Abdul Raafay </p>
logo: /assets/img/logo.png
description: 
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/abdul-raafay-syed/">LinkedIn</a> |
  <a href="https://github.com/abdulraafay">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>

theme: jekyll-theme-minimal
